require('mediaelement');
require('mediaelement/build/renderers/vimeo');
require('mediaelement/build/renderers/dailymotion');
require('mediaelement/build/renderers/soundcloud');
require('mediaelement/build/renderers/facebook');
require('mediaelement/build/renderers/twitch');
require('mediaelement/build/mediaelementplayer.min.css');
require('mediaelement/build/lang/fr');
require('@/mediaelement/nico');
